spring:
  application:
    name: config-server

  cloud:
    config.server.git:
      uri: https://github.com/HarshilChampaneri/hire-genie-config-repo
      username: HarshilChampaneri
      password: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      default-label: main

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-server:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
